### PR TITLE
perhaps absolute paths should be relative to the absolute paths…

### PR DESCRIPTION
**Pull request by ztane**
…or the `if` removed altogether?

### CODE REVIEW

**Comment by bertjwregeer** [comment]
I'd be a +1 on removing the if statement entirely. I don't think it makes sense to have it be relative to the current working directory.

Nice catch @ztane! Let's see what @mmerickel thinks before you make the change.

**Comment by huntcsg** [comment]
My memory is vague, but I think this was designed to place nicely with code here: 

[PasteDeploy / paste / deploy / loadwsgi.py:299](https://bitbucket.org/ianb/pastedeploy/src/4b27133a2a7db58b213ae55b580039c11d2055c0/paste/deploy/loadwsgi.py?at=default&fileviewer=file-view-default#loadwsgi.py-299)

That's the context within which we should evaluate this change.

**Comment by mmerickel** [comment]
ISTM that the correct impl should just be `os.path.dirname(uri.path)` always - except if there is no path in the case of something like `egg:foo`. Does anyone disagree?

**Comment by bertjwregeer** [comment]
:+1:

**Comment by mmerickel** [comment]
I dove in for a second and discovered that the relative_to is slightly different than I thought so my proposed fix above doesn't quite work. I'll need to find some more time to dive in further and figure out what the actual issue is here.

A test case sure would make this PR more useful because otherwise I have to dive into the nitty gritty details and basically fix it myself to verify that your fix works - and then I have to write a test myself - which is why fixing this is taking so long.

**Comment by mmerickel** [comment]
Okay well after a bit of research:

1. Pyramid has historically always set `relative_to=os.getcwd()`. So maybe we should just do this.

2. ISTM that the "correct" thing to do is to pass in an absolute uri and pass `os.path.dirname(uri)` as the `relative_to`. I've made https://github.com/Pylons/plaster_pastedeploy/pull/13 with this idea in mind.

**Comment by mmerickel** [comment]
Yeha ok I updated #13 to always use `os.getcwd()`. Washing my hands of this.

**Pull request closed without merging**
